name = "delicate-haze-2a16"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://killhitstudios.com"
FIREBLOCKS_VAULT_ID = "0"

# After running: wrangler kv namespace create RATE_LIMIT
# replace the id below with the returned namespace ID
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "b2227482a1d14f7baf018e468b92a71f"
